// subjects.js
export const subjects = [
  'IS104 - Systems Analysis & Design',
  'DM101 - Organization and Management Concepts',
  'CC101 - Introduction to Computing',
  'CC102 - Computer Programming 1',
  'CHF - Computer Hardware Fundamentals',
  'IS101 - Fundamentals of Information Systems',
  'CC103 - Computer Programming 2',
  'WEBDEV - Web Development',
  'CC104 - Data Structures and Algorithms',
  'IS102 - Professional Issues in Information Systems',
  'IS103 - IT Infrastructure and Network Technologies',
  'GE4 - Mathematics in the Modern World',
  'GE1 - Understanding the Self',
  'GE7 - Science, Technology and Society',
  'FIL1 - Komunikasyon sa Akademikong Filipino',
  'PE1 - Physical Fitness and Self-Testing Activities',
  'NSTP1 - National Service Training Program1',
  'DM102 - Financial Management',
  'PROFEL1 - IS Innovations & New Technologies',
  'ACCTG1 - Principle of Accounting',
  'CC105 - Information Management',
  'IS105 - Enterprise Architecture',
  'DM103 - Business Process Management',
  'QUAMET - Quantitative Methods',
  'PROFEL2 - Human Computer Interaction',
  'IS106 - IS Project Management 1',
  'CAP101 - Capstone Project 1',
  'CAP102 - Capstone Project 2',
  'AGRI 111: Introduction to Agriculture',
  'Crim 1: Intro to Criminology and Psych of Crimes',
  'PA121: Introduction to Public Administration',
  'GE 10/Elective: Living in the IT Eras',
];
